-- MySQL Script generated by MySQL Workbench
-- 05/09/15 10:40:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema brainyping
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `bg_proc_last_exec`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bg_proc_last_exec` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `proc_name` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `date_ts` INT(11) NULL DEFAULT NULL,
  `date_str` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `execution_time` DECIMAL(7,3) NULL DEFAULT NULL,
  `note` VARCHAR(500) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `hosts` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `minutes_alert` SMALLINT(6) NOT NULL DEFAULT '1',
  `alert_sent` INT(11) NULL DEFAULT NULL,
  `date_ts_db` INT(11) NOT NULL DEFAULT '0',
  `check_time_alignment` TINYINT(1) NOT NULL DEFAULT '0',
  `timeline_chart_long` TINYINT(1) NOT NULL DEFAULT '0',
  `timeline_chart_short` TINYINT(1) NOT NULL DEFAULT '0',
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `machine_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'DEFAULT',
  `db_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'DEFAULT',
  `start_run_ts` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`proc_name`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `idx_proc_name` (`proc_name` ASC),
  INDEX `idx_db_id` (`db_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bg_proc_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bg_proc_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `proc_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `ts_start` INT(11) NOT NULL,
  `ts_stop` INT(11) NOT NULL,
  `chart_value` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `chart_value_generated` TINYINT(1) NOT NULL DEFAULT '0',
  `machine_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'DEFAULT',
  `db_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'DEFAULT',
  PRIMARY KEY (`id`),
  INDEX `idx_proc_name` (`proc_name` ASC),
  INDEX `idx_chart_value_gen` (`chart_value_generated` ASC),
  INDEX `db_id` (`db_id` ASC),
  INDEX `idx_ts_stop` (`ts_stop` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 3195506
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `check_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `check_types` (
  `id` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `descr` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `enabled` TINYINT(4) NOT NULL DEFAULT '1',
  `long_descr` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `fa_icon` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `date_ts` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `common_ports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `common_ports` (
  `port` INT(11) NOT NULL,
  `name` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `enabled` TINYINT(4) NULL DEFAULT '1',
  PRIMARY KEY (`port`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `email_queue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `email_queue` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_ts` INT(11) NULL DEFAULT NULL,
  `date_str` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `subject` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `body` VARCHAR(15000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `from_` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `to_` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `bcc` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sent_date_ts` INT(11) NULL DEFAULT NULL,
  `sent_date_str` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `status` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `machine_id` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `db_id` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `token` CHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  INDEX `idx_sent_date_ts` (`sent_date_ts` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1242
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `host_checks_schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `host_checks_schedule` (
  `id_host` INT(11) NOT NULL DEFAULT '0',
  `ts_check` INT(11) NOT NULL DEFAULT '0',
  `date_check` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `status` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `daycode` INT(8) NOT NULL DEFAULT '0',
  `interval_minutes` SMALLINT(6) NOT NULL DEFAULT '0',
  `aggregated` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_host`, `ts_check`),
  INDEX `idx_id_host_daycode` (`id_host` ASC, `daycode` ASC),
  INDEX `idx_aggregated` (`aggregated` ASC),
  INDEX `idx_ts_check` (`ts_check` ASC),
  INDEX `idx_id_host_checkssched` (`id_host` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `user_contact_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_contact_types` (
  `id` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `name` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `enabled` TINYINT(11) NULL DEFAULT '1',
  `id_ai` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_ai_UNIQUE` (`id_ai` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `email_verification_code` VARCHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `email_verification_ts` INT(11) NOT NULL DEFAULT '0',
  `email_verified` TINYINT(4) NOT NULL,
  `enabled` TINYINT(4) NOT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `date_added_ts` INT(11) NOT NULL,
  `role` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL,
  `last_login_ts` INT(11) NOT NULL,
  `locked` TINYINT(4) NOT NULL DEFAULT '0',
  `public_token` VARCHAR(20) CHARACTER SET 'utf8mb4' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_email` (`email` ASC),
  UNIQUE INDEX `idx_public_token` (`public_token` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `user_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user_contacts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `contact` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `validation_token` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `validated` TINYINT(4) NULL DEFAULT NULL,
  `id_user` INT(11) NOT NULL,
  `contact_type_id` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `primary_contact` TINYINT(4) NOT NULL DEFAULT '0',
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `friendly_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '-',
  PRIMARY KEY (`id`),
  INDEX `fk_user_contacts_id_user` (`id_user` ASC),
  INDEX `fk_user_contacts_contact_type` (`contact_type_id` ASC),
  CONSTRAINT `fk_user_contacts_contact_type`
    FOREIGN KEY (`contact_type_id`)
    REFERENCES `user_contact_types` (`id`),
  CONSTRAINT `fk_user_contacts_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hosts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hosts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `host` VARCHAR(250) CHARACTER SET 'utf8' NOT NULL,
  `title` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `check_running` TINYINT(1) NULL DEFAULT '0',
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `added_ts` INT(11) NOT NULL,
  `next_check_ts` INT(11) NOT NULL,
  `last_alert_ts` INT(11) NOT NULL DEFAULT '0',
  `next_check_str` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `id_user` INT(11) NOT NULL,
  `minutes` TINYINT(4) NOT NULL,
  `port` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `log_enabled` TINYINT(1) NOT NULL DEFAULT '0',
  `check_session` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `check_started_ts` INT(11) NULL DEFAULT NULL,
  `check_started_str` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `last_check_ts` INT(11) NULL DEFAULT NULL,
  `last_check_str` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `check_result` VARCHAR(15) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `check_result_since_ts` INT(11) NULL DEFAULT NULL,
  `check_result_since_str` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `latest_results` VARCHAR(1000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `public` TINYINT(1) NULL DEFAULT '1',
  `last_check_avg` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `check_type` VARCHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `public_token` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `delete_queue` INT(11) NULL DEFAULT NULL,
  `num_contacts` TINYINT(4) NOT NULL DEFAULT '0',
  `homepage` TINYINT(1) NOT NULL DEFAULT '0',
  `check_reservation_code` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `check_reservation_ts` INT(11) NOT NULL DEFAULT '0',
  `keyword` VARCHAR(200) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `edited_ts` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_public_token` (`public_token` ASC),
  INDEX `idx_enabled` (`enabled` ASC),
  INDEX `idx_next_check_ts` (`next_check_ts` ASC),
  INDEX `idx_last_check_ts` (`last_check_ts` ASC),
  INDEX `idx_check_result` (`check_result` ASC),
  INDEX `idx_public` (`public` ASC),
  INDEX `idx_hosts_id_user` (`id_user` ASC),
  INDEX `idx_title` (`title` ASC),
  INDEX `fk_checktype` (`check_type` ASC),
  INDEX `idx_ping_running` (`check_running` ASC),
  INDEX `idx_homepage` (`homepage` ASC),
  INDEX `idx_check_res_code` (`check_reservation_code` ASC),
  INDEX `idx_next_ts_check_running` (`next_check_ts` ASC, `check_running` ASC),
  CONSTRAINT `fk_checktype`
    FOREIGN KEY (`check_type`)
    REFERENCES `check_types` (`id`),
  CONSTRAINT `fk_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1810
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `host_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `host_contacts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_host` INT(11) NULL DEFAULT NULL,
  `id_contact` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_host_contacts_id_contact` (`id_contact` ASC),
  INDEX `fk_host_contacts_id_host` (`id_host` ASC),
  CONSTRAINT `fk_host_contacts_id_contact`
    FOREIGN KEY (`id_contact`)
    REFERENCES `user_contacts` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_host_contacts_id_host`
    FOREIGN KEY (`id_host`)
    REFERENCES `hosts` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `host_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `host_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `public_token` CHAR(20) CHARACTER SET 'utf8' NOT NULL,
  `ts` INT(11) NULL DEFAULT NULL,
  `event` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `id_host` INT(11) NULL DEFAULT NULL,
  `machine_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'DEFAULT',
  `db_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'DEFAULT',
  PRIMARY KEY (`id`),
  INDEX `fk_id_host_hosts` (`public_token` ASC),
  INDEX `idx_db_id` (`db_id` ASC),
  INDEX `fk_id_host_hostlogs_idx` (`id_host` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 36592
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `host_subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `host_subscriptions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_contact_type` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `contact` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `friendly_name` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `validation_token` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '-',
  `validated` TINYINT(1) NOT NULL DEFAULT '0',
  `added_ts` INT(11) NULL DEFAULT NULL,
  `validated_ts` INT(11) NULL DEFAULT NULL,
  `id_host` INT(11) NOT NULL,
  `id_user` INT(11) NULL DEFAULT NULL,
  `id_user_contact` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_type_idx` (`id_contact_type` ASC),
  INDEX `idx_id_host` (`id_host` ASC),
  INDEX `fk_id_user_idx` (`id_user` ASC),
  INDEX `fk_id_contact_host_subs_idx` (`id_user_contact` ASC),
  CONSTRAINT `fk_contact_type_host_subs`
    FOREIGN KEY (`id_contact_type`)
    REFERENCES `user_contact_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_contact_host_subs`
    FOREIGN KEY (`id_user_contact`)
    REFERENCES `user_contacts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_host_host_subs`
    FOREIGN KEY (`id_host`)
    REFERENCES `hosts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_user_host_subs`
    FOREIGN KEY (`id_user`)
    REFERENCES `users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `process` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `date_ts` INT(11) NOT NULL,
  `date_str` VARCHAR(25) CHARACTER SET 'utf8' NOT NULL,
  `log_note` VARCHAR(500) CHARACTER SET 'utf8' NOT NULL,
  `log_level` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `session_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `log_seq` SMALLINT(6) NOT NULL,
  `machine_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'DEFAULT',
  `db_id` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'DEFAULT',
  PRIMARY KEY (`id`),
  INDEX `idx_db_id` (`db_id` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 38618
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `results` (
  `id_host` INT(11) NOT NULL,
  `result` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `requests` TINYINT(1) NULL DEFAULT NULL,
  `requests_ok` TINYINT(1) NULL DEFAULT NULL,
  `reply_best` DECIMAL(9,3) NULL DEFAULT NULL,
  `reply_average` DECIMAL(9,3) NULL DEFAULT NULL,
  `reply_worst` DECIMAL(9,3) NULL DEFAULT NULL,
  `current_date_ts` INT(11) NULL DEFAULT NULL,
  `current_date_str` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ts_check_triggered` INT(11) NULL DEFAULT NULL,
  `ts_check_delay` INT(11) NULL DEFAULT NULL,
  `session_id` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `host` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `port` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `source` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `public` TINYINT(1) NULL DEFAULT NULL,
  `ip` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `daycode` INT(11) NULL DEFAULT NULL,
  `aggregated` TINYINT(4) NOT NULL DEFAULT '0',
  `seconds_previous_result` INT(11) NOT NULL DEFAULT '0',
  `details` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `result_was` VARCHAR(15) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `time_spent` DECIMAL(6,3) NOT NULL DEFAULT '0.000',
  `error_code` CHAR(20) CHARACTER SET 'utf8' NULL DEFAULT '-',
  `machine_id` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `db_id` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `current_date_ts_00` INT(11) NULL DEFAULT NULL,
  `current_date_ts_000` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_id_host` (`id_host` ASC),
  INDEX `idx_daycode` (`daycode` ASC),
  INDEX `idx_aggregated` (`aggregated` ASC),
  INDEX `idx_aggregated_daycode` (`aggregated` ASC, `daycode` ASC),
  INDEX `idx_daycode_idhost` (`daycode` ASC, `id_host` ASC),
  INDEX `idx_id_host_current_date` (`id_host` ASC, `current_date_ts` ASC),
  INDEX `fk_ts_check_id_host_scheduled_check` (`id_host` ASC, `ts_check_triggered` ASC),
  INDEX `idx_current_date_ts` (`current_date_ts` ASC),
  INDEX `idx_current_date_ts_00` (`current_date_ts_00` ASC),
  INDEX `idx_current_date_ts_000` (`current_date_ts_000` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 37057665
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `results_daily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `results_daily` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `daycode` INT(11) NULL DEFAULT NULL,
  `id_host` INT(11) NULL DEFAULT NULL,
  `uptime` MEDIUMINT(9) NULL DEFAULT NULL,
  `downtime` MEDIUMINT(9) NULL DEFAULT NULL,
  `unknowntime` MEDIUMINT(9) NULL DEFAULT NULL,
  `monitor_off` MEDIUMINT(9) NULL DEFAULT NULL,
  `generated_ts` INT(11) NULL DEFAULT NULL,
  `planned_checks` SMALLINT(6) NULL DEFAULT NULL,
  `completed_checks` SMALLINT(6) NULL DEFAULT NULL,
  `day_details` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `log` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ts` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_daycode_idhost` (`daycode` ASC, `id_host` ASC),
  INDEX `idx_idhost` (`id_host` ASC),
  INDEX `idx_daycode` (`daycode` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 129009
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `results_latest_24h`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `results_latest_24h` (
  `id_host` INT(11) NOT NULL,
  `ts_trunc` DOUBLE NULL DEFAULT NULL,
  `reply_avg` DECIMAL(10,3) NULL DEFAULT NULL,
  `NOK` DECIMAL(23,0) NULL DEFAULT NULL,
  `TOT` DECIMAL(23,0) NULL DEFAULT NULL,
  `generated_ts` INT(11) NOT NULL DEFAULT '0',
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `idx_id_host` (`id_host` ASC),
  INDEX `idx_ts_trunc` (`ts_trunc` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 12390915
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `results_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `results_temp` (
  `id_host` INT(11) NOT NULL,
  `result` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `requests` TINYINT(1) NULL DEFAULT NULL,
  `requests_ok` TINYINT(1) NULL DEFAULT NULL,
  `reply_best` DECIMAL(9,3) NULL DEFAULT NULL,
  `reply_average` DECIMAL(9,3) NULL DEFAULT NULL,
  `reply_worst` DECIMAL(9,3) NULL DEFAULT NULL,
  `current_date_ts` INT(11) NULL DEFAULT NULL,
  `current_date_str` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `ts_check_triggered` INT(11) NULL DEFAULT NULL,
  `ts_check_delay` INT(11) NULL DEFAULT NULL,
  `session_id` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `host` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `port` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `source` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `public` TINYINT(1) NULL DEFAULT NULL,
  `ip` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `daycode` INT(11) NULL DEFAULT NULL,
  `aggregated` TINYINT(4) NOT NULL DEFAULT '0',
  `seconds_previous_result` INT(11) NOT NULL DEFAULT '0',
  `details` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `result_was` VARCHAR(15) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `time_spent` DECIMAL(6,3) NOT NULL DEFAULT '0.000',
  `error_code` CHAR(20) CHARACTER SET 'utf8' NULL DEFAULT '-',
  `machine_id` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `db_id` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `current_date_ts_00` INT(11) NULL DEFAULT NULL,
  `current_date_ts_000` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_id_host` (`id_host` ASC),
  INDEX `idx_daycode` (`daycode` ASC),
  INDEX `idx_aggregated` (`aggregated` ASC),
  INDEX `idx_aggregated_daycode` (`aggregated` ASC, `daycode` ASC),
  INDEX `idx_daycode_idhost` (`daycode` ASC, `id_host` ASC),
  INDEX `idx_id_host_current_date` (`id_host` ASC, `current_date_ts` ASC),
  INDEX `fk_ts_check_id_host_scheduled_check` (`id_host` ASC, `ts_check_triggered` ASC),
  INDEX `idx_current_date_ts` (`current_date_ts` ASC),
  INDEX `idx_current_date_ts_00` (`current_date_ts_00` ASC),
  INDEX `idx_current_date_ts_000` (`current_date_ts_000` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 37057533
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `stats_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stats_data` (
  `id_stat` VARCHAR(30) CHARACTER SET 'utf8' NOT NULL,
  `stat_value` MEDIUMTEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `generated_ts` INT(11) NOT NULL DEFAULT '0',
  `generated_str` CHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `generated_time_spent` DECIMAL(7,3) NULL DEFAULT NULL,
  `stat_descr` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `update_interval_minutes` SMALLINT(6) NOT NULL DEFAULT '1440',
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `last_ts_trunc` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `idx_id_stats` (`id_stat` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sync_tables_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sync_tables_config` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `int_schema` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `int_table` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'Source table name',
  `last_sync_ts` INT(11) NOT NULL DEFAULT '0' COMMENT 'last sync timestamp',
  `last_sync_str` CHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sync_interval` DECIMAL(5,1) NOT NULL COMMENT 'sync table every XX minutes',
  `enabled` TINYINT(1) NOT NULL DEFAULT '1',
  `time_spent` DECIMAL(7,3) NOT NULL DEFAULT '0.000',
  `friendly_name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `lookup_field` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `sync_reverse` TINYINT(1) NOT NULL DEFAULT '0',
  `ext_schema` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `ext_table` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT 'destination table name',
  `ext_host` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `ext_port` INT(11) NOT NULL,
  `ext_user` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `ext_pwd` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `ext_charset` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT 'utf-8',
  `ext_timezone_offset` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '+1:00' COMMENT 'something like \'+1:00\' or \'-2:00\'',
  `nrecs` INT(11) NOT NULL,
  `nrec_insert` INT(11) NOT NULL DEFAULT '0',
  `nrec_update` INT(11) NOT NULL DEFAULT '0',
  `nrec_delete` INT(11) NULL DEFAULT NULL,
  `force_run` TINYINT(1) NOT NULL DEFAULT '0',
  `local_sync` TINYINT(1) NOT NULL DEFAULT '0',
  `sync_will_merge` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Means that destination table will me a result of multiple identic tables merged.  When this flag is 1 interface will look for a field named db_id that is the source db identifier.\nAlso, destination table should not have a unique primary key as the source because id keys could be duplicated.',
  `insert_` TINYINT(1) NOT NULL DEFAULT '0',
  `update_` TINYINT(1) NOT NULL DEFAULT '0',
  `update_cursor_field` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `update_cursor_value_included` TINYINT(1) NOT NULL DEFAULT '0',
  `delete_by_cursor` TINYINT(1) NOT NULL DEFAULT '0',
  `delete_by_lookup` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Perform a \"NOT IN\" operation so use it only with table not so big....',
  `delete_cursor_field` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `return_code` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `return_desc` VARCHAR(2000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `friendly_name_UNIQUE` (`friendly_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `sync_tables_logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sync_tables_logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date_ts` INT(11) NULL DEFAULT NULL,
  `date_str` VARCHAR(25) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `step_` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `friendly_name` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `friendly_group_name` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `group_seq` TINYINT(2) NULL DEFAULT NULL,
  `time_spent` DECIMAL(8,3) NULL DEFAULT NULL,
  `nrec_insert` INT(11) NULL DEFAULT NULL,
  `nrec_update` INT(11) NULL DEFAULT NULL,
  `nrec_delete` INT(11) NULL DEFAULT NULL,
  `return_code` VARCHAR(10) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `return_descr` VARCHAR(2000) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `machine_id` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `db_id` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 635878
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Placeholder table for view `vw_checks_schedule_with_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vw_checks_schedule_with_results` (`id_host` INT, `daycode` INT, `date_check` INT, `interval_minutes` INT, `ts_check` INT, `current_date_ts` INT, `result` INT, `result_was` INT, `source` INT);

-- -----------------------------------------------------
-- Placeholder table for view `vw_checks_schedule_with_results_temp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vw_checks_schedule_with_results_temp` (`id_host` INT, `daycode` INT, `date_check` INT, `interval_minutes` INT, `ts_check` INT, `current_date_ts` INT, `result` INT, `result_was` INT, `source` INT);

-- -----------------------------------------------------
-- View `vw_checks_schedule_with_results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vw_checks_schedule_with_results`;
CREATE  OR REPLACE VIEW `vw_checks_schedule_with_results` AS select `hcs`.`id_host` AS `id_host`,`hcs`.`daycode` AS `daycode`,`hcs`.`date_check` AS `date_check`,`hcs`.`interval_minutes` AS `interval_minutes`,`hcs`.`ts_check` AS `ts_check`,ifnull(`r`.`current_date_ts`,'-') AS `current_date_ts`,ifnull(`r`.`result`,'-') AS `result`,ifnull(`r`.`result_was`,'-') AS `result_was`,ifnull(`r`.`source`,'-') AS `source` from (`host_checks_schedule` `hcs` left join `results` `r` on(((`hcs`.`id_host` = `r`.`id_host`) and (`hcs`.`ts_check` = `r`.`ts_check_triggered`))));

-- -----------------------------------------------------
-- View `vw_checks_schedule_with_results_temp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vw_checks_schedule_with_results_temp`;
CREATE  OR REPLACE  VIEW `vw_checks_schedule_with_results_temp` AS select `hcs`.`id_host` AS `id_host`,`hcs`.`daycode` AS `daycode`,`hcs`.`date_check` AS `date_check`,`hcs`.`interval_minutes` AS `interval_minutes`,`hcs`.`ts_check` AS `ts_check`,ifnull(`r`.`current_date_ts`,'-') AS `current_date_ts`,ifnull(`r`.`result`,'-') AS `result`,ifnull(`r`.`result_was`,'-') AS `result_was`,ifnull(`r`.`source`,'-') AS `source` from (`host_checks_schedule` `hcs` left join `results_temp` `r` on(((`hcs`.`id_host` = `r`.`id_host`) and (`hcs`.`ts_check` = `r`.`ts_check_triggered`))));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
